
# training
deepspeed --include localhost:0,1,6,7 --master_port=25002 run.py \
  --version weight/HuatuoGPT-Vision-7B-Qwen2.5VL \
  --vision_pretrained runs/pretrainseg4_bp_224_1e-05_BG62_RA816_lmw1.0_sr1_mpT/hf_model/pytorch_model.bin \
  --dataset_dir /mnt/disk2/hwj/Tails/dataset \
  --dataset "refer_seg||vqa" \
  --refer_seg_data "IMed361M" \
  --vqa_data "PubMedVision||MIMIC||SLAKE||PMC_VQA||vqa-rad||path-vqa" \
  --val_dataset "refer_seg||vqa" \
  --sample_rates "1,1" \
  --batch_size 4 \
  --grad_accumulation_steps 2 \
  --image_size 256 \
  --lr 1e-5 \
  --lr_vl 5e-6 \
  --epochs 5 \
  --lora_r 8 \
  --lora_alpha 16 \
  --exp_name exp \
  --seed 58

# inference
deepspeed --include localhost:0,1,6,7 --master_port=24005 run.py --epochs 3 --divided_save 0.025 --batch_size 4 --lm_weight 1.0 --lr 1e-5 --lr_vl 5e-6 --sample_rates "1,1" --promptype tbp --exp_name release --image_size 256 --aware_loss --tail_loop --test --val_dataset refer_seg --val_batch_size 1;
deepspeed --include localhost:0,1,6,7 --master_port=24002 run.py --epochs 3 --divided_save 0.025 --batch_size 4 --lm_weight 1.0 --lr 1e-5 --lr_vl 5e-6 --sample_rates "1,1" --promptype tbp --exp_name release --image_size 256 --test --val_dataset refer_seg --val_batch_size 1;
deepspeed --include localhost:0,1,6,7 --master_port=24002 run.py --epochs 3 --divided_save 0.025 --batch_size 4 --lm_weight 1.0 --lr 1e-5 --lr_vl 5e-6 --sample_rates "1,1" --promptype tbp --exp_name release --image_size 256 --test --val_dataset vqa --vqa_data PubMedVision;
deepspeed --include localhost:0,1,6,7 --master_port=24002 run.py --epochs 3 --divided_save 0.025 --batch_size 4 --lm_weight 1.0 --lr 1e-5 --lr_vl 5e-6 --sample_rates "1,1" --promptype tbp --exp_name release --image_size 256 --test --val_dataset vqa --vqa_data MIMIC;
deepspeed --include localhost:0,1,6,7 --master_port=24002 run.py --epochs 3 --divided_save 0.025 --batch_size 4 --lm_weight 1.0 --lr 1e-5 --lr_vl 5e-6 --sample_rates "1,1" --promptype tbp --exp_name release --image_size 256 --test --val_dataset vqa --vqa_data PMC_VQA;
deepspeed --include localhost:0,1,6,7 --master_port=24002 run.py --epochs 3 --divided_save 0.025 --batch_size 4 --lm_weight 1.0 --lr 1e-5 --lr_vl 5e-6 --sample_rates "1,1" --promptype tbp --exp_name release --image_size 256 --test --val_dataset vqa --vqa_data SLAKE;
deepspeed --include localhost:0,1,6,7 --master_port=24002 run.py --epochs 3 --divided_save 0.025 --batch_size 4 --lm_weight 1.0 --lr 1e-5 --lr_vl 5e-6 --sample_rates "1,1" --promptype tbp --exp_name release --image_size 256 --test --val_dataset vqa --vqa_data vqa-rad;
deepspeed --include localhost:0,1,6,7 --master_port=24002 run.py --epochs 3 --divided_save 0.025 --batch_size 4 --lm_weight 1.0 --lr 1e-5 --lr_vl 5e-6 --sample_rates "1,1" --promptype tbp --exp_name release --image_size 256 --test --val_dataset vqa --vqa_data path-vqa;
deepspeed --include localhost:0,1,6,7 --master_port=24002 run.py --epochs 3 --divided_save 0.025 --batch_size 4 --lm_weight 1.0 --lr 1e-5 --lr_vl 5e-6 --sample_rates "1,1" --promptype tbp --exp_name release --image_size 256 --test --val_dataset vqa --vqa_data cxr-lt;
deepspeed --include localhost:0,1,6,7 --master_port=24002 run.py --epochs 3 --divided_save 0.025 --batch_size 4 --lm_weight 1.0 --lr 1e-5 --lr_vl 5e-6 --sample_rates "1,1" --promptype tbp --exp_name release --image_size 256 --test --val_dataset vqa --vqa_data isic2018;
deepspeed --include localhost:0,1,6,7 --master_port=24002 run.py --epochs 3 --divided_save 0.025 --batch_size 4 --lm_weight 1.0 --lr 1e-5 --lr_vl 5e-6 --sample_rates "1,1" --promptype tbp --exp_name release --image_size 256 --test --val_dataset vqa --vqa_data isic2019;
deepspeed --include localhost:0,1,6,7 --master_port=24002 run.py --epochs 3 --divided_save 0.025 --batch_size 4 --lm_weight 1.0 --lr 1e-5 --lr_vl 5e-6 --sample_rates "1,1" --promptype tbp --exp_name release --image_size 256 --test --val_dataset vqa --vqa_data SLAKE --openclosetype open;
deepspeed --include localhost:0,1,6,7 --master_port=24002 run.py --epochs 3 --divided_save 0.025 --batch_size 4 --lm_weight 1.0 --lr 1e-5 --lr_vl 5e-6 --sample_rates "1,1" --promptype tbp --exp_name release --image_size 256 --test --val_dataset vqa --vqa_data vqa-rad --openclosetype open;
deepspeed --include localhost:0,1,6,7 --master_port=24002 run.py --epochs 3 --divided_save 0.025 --batch_size 4 --lm_weight 1.0 --lr 1e-5 --lr_vl 5e-6 --sample_rates "1,1" --promptype tbp --exp_name release --image_size 256 --test --val_dataset vqa --vqa_data path-vqa --openclosetype open;
deepspeed --include localhost:0,1,6,7 --master_port=24002 run.py --epochs 3 --divided_save 0.025 --batch_size 4 --lm_weight 1.0 --lr 1e-5 --lr_vl 5e-6 --sample_rates "1,1" --promptype tbp --exp_name release --image_size 256 --test --val_dataset vqa --vqa_data SLAKE --openclosetype close;
deepspeed --include localhost:0,1,6,7 --master_port=24002 run.py --epochs 3 --divided_save 0.025 --batch_size 4 --lm_weight 1.0 --lr 1e-5 --lr_vl 5e-6 --sample_rates "1,1" --promptype tbp --exp_name release --image_size 256 --test --val_dataset vqa --vqa_data vqa-rad --openclosetype close;
deepspeed --include localhost:0,1,6,7 --master_port=24002 run.py --epochs 3 --divided_save 0.025 --batch_size 4 --lm_weight 1.0 --lr 1e-5 --lr_vl 5e-6 --sample_rates "1,1" --promptype tbp --exp_name release --image_size 256 --test --val_dataset vqa --vqa_data path-vqa --openclosetype close;
deepspeed --include localhost:0,1,6,7 --master_port=24002 run.py --epochs 3 --divided_save 0.025 --batch_size 4 --lm_weight 1.0 --lr 1e-5 --lr_vl 5e-6 --sample_rates "1,1" --promptype tbp --exp_name release --image_size 256 --test --val_dataset vqa --vqa_data PMC_VQA --modality "computed tomography";
deepspeed --include localhost:0,1,6,7 --master_port=24002 run.py --epochs 3 --divided_save 0.025 --batch_size 4 --lm_weight 1.0 --lr 1e-5 --lr_vl 5e-6 --sample_rates "1,1" --promptype tbp --exp_name release --image_size 256 --test --val_dataset vqa --vqa_data PMC_VQA --modality "magnetic resonance imaging";
deepspeed --include localhost:0,1,6,7 --master_port=24002 run.py --epochs 3 --divided_save 0.025 --batch_size 4 --lm_weight 1.0 --lr 1e-5 --lr_vl 5e-6 --sample_rates "1,1" --promptype tbp --exp_name release --image_size 256 --test --val_dataset vqa --vqa_data PMC_VQA --modality "microscopy images";
deepspeed --include localhost:0,1,6,7 --master_port=24002 run.py --epochs 3 --divided_save 0.025 --batch_size 4 --lm_weight 1.0 --lr 1e-5 --lr_vl 5e-6 --sample_rates "1,1" --promptype tbp --exp_name release --image_size 256 --test --val_dataset vqa --vqa_data PMC_VQA --modality "ultrasound";
deepspeed --include localhost:0,1,6,7 --master_port=24002 run.py --epochs 3 --divided_save 0.025 --batch_size 4 --lm_weight 1.0 --lr 1e-5 --lr_vl 5e-6 --sample_rates "1,1" --promptype tbp --exp_name release --image_size 256 --test --val_dataset vqa --vqa_data PMC_VQA --modality "PET";
deepspeed --include localhost:0,1,6,7 --master_port=24002 run.py --epochs 3 --divided_save 0.025 --batch_size 4 --lm_weight 1.0 --lr 1e-5 --lr_vl 5e-6 --sample_rates "1,1" --promptype tbp --exp_name release --image_size 256 --test --val_dataset vqa --vqa_data PMC_VQA --modality "ANGIOGRAPHY";
deepspeed --include localhost:0,1,6,7 --master_port=24002 run.py --epochs 3 --divided_save 0.025 --batch_size 4 --lm_weight 1.0 --lr 1e-5 --lr_vl 5e-6 --sample_rates "1,1" --promptype tbp --exp_name release --image_size 256 --test --val_dataset vqa --vqa_data PMC_VQA --modality "PET_CT";
deepspeed --include localhost:0,1,6,7 --master_port=24002 run.py --epochs 3 --divided_save 0.025 --batch_size 4 --lm_weight 1.0 --lr 1e-5 --lr_vl 5e-6 --sample_rates "1,1" --promptype tbp --exp_name release --image_size 256 --test --val_dataset vqa --vqa_data PMC_VQA --modality "fundus photography";
deepspeed --include localhost:0,1,6,7 --master_port=24002 run.py --epochs 3 --divided_save 0.025 --batch_size 4 --lm_weight 1.0 --lr 1e-5 --lr_vl 5e-6 --sample_rates "1,1" --promptype tbp --exp_name release --image_size 256 --test --val_dataset vqa --vqa_data PMC_VQA --modality "optical coherence tomography";
deepspeed --include localhost:0,1,6,7 --master_port=24002 run.py --epochs 3 --divided_save 0.025 --batch_size 4 --lm_weight 1.0 --lr 1e-5 --lr_vl 5e-6 --sample_rates "1,1" --promptype tbp --exp_name release --image_size 256 --test --val_dataset vqa --vqa_data PMC_VQA --modality "endoscopy";
deepspeed --include localhost:0,1,6,7 --master_port=24002 run.py --epochs 3 --divided_save 0.025 --batch_size 4 --lm_weight 1.0 --lr 1e-5 --lr_vl 5e-6 --sample_rates "1,1" --promptype tbp --exp_name release --image_size 256 --test --val_dataset vqa --vqa_data PMC_VQA --modality "infrared reflectance imaging";
deepspeed --include localhost:0,1,6,7 --master_port=24002 run.py --epochs 3 --divided_save 0.025 --batch_size 4 --lm_weight 1.0 --lr 1e-5 --lr_vl 5e-6 --sample_rates "1,1" --promptype tbp --exp_name release --image_size 256 --test --val_dataset vqa --vqa_data PMC_VQA --modality "digital photography";
deepspeed --include localhost:0,1,6,7 --master_port=24002 run.py --epochs 3 --divided_save 0.025 --batch_size 4 --lm_weight 1.0 --lr 1e-5 --lr_vl 5e-6 --sample_rates "1,1" --promptype tbp --exp_name release --image_size 256 --test --val_dataset vqa --vqa_data PMC_VQA --modality "MAMMOGRAPHY";
deepspeed --include localhost:0,1,6,7 --master_port=24002 run.py --epochs 3 --divided_save 0.025 --batch_size 4 --lm_weight 1.0 --lr 1e-5 --lr_vl 5e-6 --sample_rates "1,1" --promptype tbp --exp_name release --image_size 256 --test --val_dataset vqa --vqa_data PMC_VQA --modality "FLUOROSCOPY";
deepspeed --include localhost:0,1,6,7 --master_port=24002 run.py --epochs 3 --divided_save 0.025 --batch_size 4 --lm_weight 1.0 --lr 1e-5 --lr_vl 5e-6 --sample_rates "1,1" --promptype tbp --exp_name release --image_size 256 --test --val_dataset vqa --vqa_data PMC_VQA --modality "DSA";
deepspeed --include localhost:0,1,6,7 --master_port=24002 run.py --epochs 3 --divided_save 0.025 --batch_size 4 --lm_weight 1.0 --lr 1e-5 --lr_vl 5e-6 --sample_rates "1,1" --promptype tbp --exp_name release --image_size 256 --test --val_dataset vqa --vqa_data PMC_VQA --modality "SCINTIGRAPHY";
deepspeed --include localhost:0,1,6,7 --master_port=24002 run.py --epochs 3 --divided_save 0.025 --batch_size 4 --lm_weight 1.0 --lr 1e-5 --lr_vl 5e-6 --sample_rates "1,1" --promptype tbp --exp_name release --image_size 256 --test --val_dataset vqa --vqa_data PMC_VQA --modality "PHOTOACOUSTIC";
deepspeed --include localhost:0,1,6,7 --master_port=24002 run.py --epochs 3 --divided_save 0.025 --batch_size 4 --lm_weight 1.0 --lr 1e-5 --lr_vl 5e-6 --sample_rates "1,1" --promptype tbp --exp_name release --image_size 256 --test --val_dataset vqa --vqa_data PMC_VQA --modality "PET_MRI";
deepspeed --include localhost:0,1,6,7 --master_port=24002 run.py --epochs 3 --divided_save 0.025 --batch_size 4 --lm_weight 1.0 --lr 1e-5 --lr_vl 5e-6 --sample_rates "1,1" --promptype tbp --exp_name release --image_size 256 --test --val_dataset vqa --vqa_data PMC_VQA --modality "ELASTOGRAPHY";
deepspeed --include localhost:0,1,6,7 --master_port=24002 run.py --epochs 3 --divided_save 0.025 --batch_size 4 --lm_weight 1.0 --lr 1e-5 --lr_vl 5e-6 --sample_rates "1,1" --promptype tbp --exp_name release --image_size 256 --test --val_dataset vqa --vqa_data PMC_VQA --modality "dermoscopy";
deepspeed --include localhost:0,1,6,7 --master_port=24002 run.py --epochs 3 --divided_save 0.025 --batch_size 4 --lm_weight 1.0 --lr 1e-5 --lr_vl 5e-6 --sample_rates "1,1" --promptype tbp --exp_name release --image_size 256 --test --val_dataset vqa --vqa_data PMC_VQA --modality "others";
deepspeed --include localhost:0,1,6,7 --master_port=24002 run.py --epochs 3 --divided_save 0.025 --batch_size 4 --lm_weight 1.0 --lr 1e-5 --lr_vl 5e-6 --sample_rates "1,1" --promptype tbp --exp_name release --image_size 256 --test --val_dataset vqa --vqa_data PMC_VQA --modality "x-ray";
deepspeed --include localhost:0,1,6,7 --master_port=24002 run.py --epochs 3 --divided_save 0.025 --batch_size 4 --lm_weight 1.0 --lr 1e-5 --lr_vl 5e-6 --sample_rates "1,1" --promptype tbp --exp_name release --image_size 256 --test --val_dataset vqa --vqa_data SLAKE --modality "MRI";
deepspeed --include localhost:0,1,6,7 --master_port=24002 run.py --epochs 3 --divided_save 0.025 --batch_size 4 --lm_weight 1.0 --lr 1e-5 --lr_vl 5e-6 --sample_rates "1,1" --promptype tbp --exp_name release --image_size 256 --test --val_dataset vqa --vqa_data SLAKE --modality "CT";
deepspeed --include localhost:0,1,6,7 --master_port=24002 run.py --epochs 3 --divided_save 0.025 --batch_size 4 --lm_weight 1.0 --lr 1e-5 --lr_vl 5e-6 --sample_rates "1,1" --promptype tbp --exp_name release --image_size 256 --test --val_dataset vqa --vqa_data SLAKE --modality "X-Ray";
deepspeed --include localhost:0,1,6,7 --master_port=24002 run.py --epochs 3 --divided_save 0.025 --batch_size 4 --lm_weight 1.0 --lr 1e-5 --lr_vl 5e-6 --sample_rates "1,1" --promptype tbp --exp_name release --image_size 256 --test --val_dataset vqa --vqa_data PubMedVision --modality "computed tomography";
deepspeed --include localhost:0,1,6,7 --master_port=24002 run.py --epochs 3 --divided_save 0.025 --batch_size 4 --lm_weight 1.0 --lr 1e-5 --lr_vl 5e-6 --sample_rates "1,1" --promptype tbp --exp_name release --image_size 256 --test --val_dataset vqa --vqa_data PubMedVision --modality "dermoscopy";
deepspeed --include localhost:0,1,6,7 --master_port=24002 run.py --epochs 3 --divided_save 0.025 --batch_size 4 --lm_weight 1.0 --lr 1e-5 --lr_vl 5e-6 --sample_rates "1,1" --promptype tbp --exp_name release --image_size 256 --test --val_dataset vqa --vqa_data PubMedVision --modality "digital photography";
deepspeed --include localhost:0,1,6,7 --master_port=24002 run.py --epochs 3 --divided_save 0.025 --batch_size 4 --lm_weight 1.0 --lr 1e-5 --lr_vl 5e-6 --sample_rates "1,1" --promptype tbp --exp_name release --image_size 256 --test --val_dataset vqa --vqa_data PubMedVision --modality "endoscopy";
deepspeed --include localhost:0,1,6,7 --master_port=24002 run.py --epochs 3 --divided_save 0.025 --batch_size 4 --lm_weight 1.0 --lr 1e-5 --lr_vl 5e-6 --sample_rates "1,1" --promptype tbp --exp_name release --image_size 256 --test --val_dataset vqa --vqa_data PubMedVision --modality "fundus photography";
deepspeed --include localhost:0,1,6,7 --master_port=24002 run.py --epochs 3 --divided_save 0.025 --batch_size 4 --lm_weight 1.0 --lr 1e-5 --lr_vl 5e-6 --sample_rates "1,1" --promptype tbp --exp_name release --image_size 256 --test --val_dataset vqa --vqa_data PubMedVision --modality "infrared reflectance imaging";
deepspeed --include localhost:0,1,6,7 --master_port=24002 run.py --epochs 3 --divided_save 0.025 --batch_size 4 --lm_weight 1.0 --lr 1e-5 --lr_vl 5e-6 --sample_rates "1,1" --promptype tbp --exp_name release --image_size 256 --test --val_dataset vqa --vqa_data PubMedVision --modality "magnetic resonance imaging";
deepspeed --include localhost:0,1,6,7 --master_port=24002 run.py --epochs 3 --divided_save 0.025 --batch_size 4 --lm_weight 1.0 --lr 1e-5 --lr_vl 5e-6 --sample_rates "1,1" --promptype tbp --exp_name release --image_size 256 --test --val_dataset vqa --vqa_data PubMedVision --modality "microfluidic device";
deepspeed --include localhost:0,1,6,7 --master_port=24002 run.py --epochs 3 --divided_save 0.025 --batch_size 4 --lm_weight 1.0 --lr 1e-5 --lr_vl 5e-6 --sample_rates "1,1" --promptype tbp --exp_name release --image_size 256 --test --val_dataset vqa --vqa_data PubMedVision --modality "microscopy images";
deepspeed --include localhost:0,1,6,7 --master_port=24002 run.py --epochs 3 --divided_save 0.025 --batch_size 4 --lm_weight 1.0 --lr 1e-5 --lr_vl 5e-6 --sample_rates "1,1" --promptype tbp --exp_name release --image_size 256 --test --val_dataset vqa --vqa_data PubMedVision --modality "optical coherence tomography";
deepspeed --include localhost:0,1,6,7 --master_port=24002 run.py --epochs 3 --divided_save 0.025 --batch_size 4 --lm_weight 1.0 --lr 1e-5 --lr_vl 5e-6 --sample_rates "1,1" --promptype tbp --exp_name release --image_size 256 --test --val_dataset vqa --vqa_data PubMedVision --modality "others"; 
deepspeed --include localhost:0,1,6,7 --master_port=24002 run.py --epochs 3 --divided_save 0.025 --batch_size 4 --lm_weight 1.0 --lr 1e-5 --lr_vl 5e-6 --sample_rates "1,1" --promptype tbp --exp_name release --image_size 256 --test --val_dataset vqa --vqa_data PubMedVision --modality "ultrasound";

